// NWS lesson content: one-thing-per-screen lesson flows.
// Each lesson is an ordered list of steps. The lesson player in app/course-ui.js
// renders one step per screen and auto-appends an "end and review" summary.
// Step types:
//   teach   {h, body}                    - concept + reasoning
//   example {h, story, points[]}         - worked example, Maya walks through it
//   try     {q, choices:[{label,ok}], hint, good, bad, why} - one question, feedback, mini explanation
//   sort    {h, body, buckets[], items:[{label,a,why}]}     - interactive animated sorting
//   tool    {screen, h, body, cta}       - hands-on in the real tool, then continue
// Review answers persist to sessionStorage only; they are not mastery evidence.

export const LESSON_CONTENT={
/* ================= MODULE 1: Money Foundations ================= */
'nws-routine':{intro:'Sort every dollar before you spend it: Needs, Wants, Savings.',steps:[
 {t:'teach',h:'Money needs a job before you spend it',
  body:'<p>Most money stress is not a math problem. It is a <b>sorting</b> problem: dollars without a job get spent on whatever shows up first.</p><p>The NWS routine gives every dollar a job:</p><ul><li><b>Need</b> - keeps you safe, healthy, or functioning <i>right now</i>.</li><li><b>Want</b> - nice to have, but life works without it.</li><li><b>Savings</b> - money moved to later, for a goal or a surprise.</li></ul><p>This is not about being "good with money." It is a decision tool: sort first, then decide.</p>'},
 {t:'teach',h:'The 4-step routine',
  body:'<ol><li><b>List</b> what is coming: bills, pay, anything pending.</li><li><b>Sort</b> each one into Need, Want, or Savings.</li><li><b>Protect</b> Needs first, then move Savings aside <i>before</i> spending on Wants.</li><li><b>Spend</b> what is left on Wants - without guilt. That is what it is for.</li></ol><p>Order matters. Wants are decided <i>last</i>, from what is left - never first, from what is visible.</p>'},
 {t:'sort',h:'Sort it: Maya\u2019s week',body:'<p>Maya has her week in front of her. Sort each item into the right bucket. Watch what the routine protects.</p>',
  buckets:['Need','Want','Savings'],
  items:[
   {label:'Bus pass to get to work',a:'need',why:'Without it she cannot earn. Work transport is a Need.'},
   {label:'Groceries for the week',a:'need',why:'Food that keeps her going is a Need - not fancy food, but food.'},
   {label:'New headphones (old ones work fine)',a:'want',why:'Nice to have. The old ones work, so this is a Want.'},
   {label:'$10 into her emergency fund',a:'savings',why:'Money moved to later. Savings is its own bucket.'},
   {label:'Phone bill',a:'need',why:'Required to keep service she depends on. A Need.'},
   {label:'Concert ticket',a:'want',why:'Fun, memorable - and optional. A Want.'},
   {label:'Prescription refill',a:'need',why:'Health comes first. A Need, no debate.'},
   {label:'Daily fancy coffee',a:'want',why:'A small daily Want. Fine - but only from what is left after Needs and Savings.'}]},
 {t:'try',q:'Maya\u2019s old backpack broke and she needs one for school. A plain $25 backpack is a\u2026',
  choices:[{label:'Need',ok:true},{label:'Want',ok:false},{label:'Savings - buying the plain one saves money',ok:false},{label:'Savings',ok:false}],
  hint:'Ask: what is it for, right now?',
  good:'Right. She needs it for school - that is a Need.',
  bad:'Not quite. She needs it for school - function first.',
  why:'A plain backpack that lets her do school is a Need. The <i>fancy</i> $80 version would be a Want hiding inside a Need.'},
 {t:'try',q:'Maya\u2019s phone: she needs it for work shifts, but mostly uses it for games. How should she sort it?',
  choices:[{label:'It is all a Need',ok:false},{label:'Whichever she uses more - majority rules',ok:false},{label:'It is all a Want',ok:false},{label:'Split it: the work part is a Need, the games part is a Want',ok:true}],
  hint:'One item can hold two jobs.',
  good:'Exactly. Sort by what it is for, not by the object itself.',
  bad:'Look closer - the phone does two jobs. Sort each job separately.',
  why:'The work capability is a Need; the gaming is a Want. When one purchase does both, sort the <i>reasons</i>, not the thing.'},
 {t:'try',q:'Maya gets a $50 birthday gift from her aunt, with no strings attached. What does the routine say to do first?',
  choices:[{label:'Send it straight to Wants - gift money is fun money',ok:false},{label:'Run it through the routine like any other money: Needs, then Savings, then Wants',ok:true},{label:'Put all of it in Savings - gifts should never be spent',ok:false},{label:'It does not count - only paychecks get sorted',ok:false}],
  hint:'Does the routine care where the money came from?',
  good:'Right. The routine sorts every dollar, no matter the source.',
  bad:'Windfalls feel like free money, but they spend the same. Sort it like the rest.',
  why:'Gift money, found money, side-gig money - it all spends the same. Running it through Needs \u2192 Savings \u2192 Wants keeps a fun surprise from quietly becoming regret.'},
 {t:'try',q:'Maya\u2019s laptop charger dies the night before a paper is due. A replacement costs $35 and she has $40 of flexible money. What is the call?',
  choices:[{label:'It is electronics, so it is a Want - make do without it',ok:false},{label:'It is a Need - school depends on it, and the flexible money covers it',ok:true},{label:'It is Savings - a charger lasts for years, so it is an investment',ok:false},{label:'Never spend flexible money this fast - wait a week',ok:false}],
  hint:'What is it for, right now?',
  good:'Right. Function first, and the money is there.',
  bad:'Ask what it is for right now: without the charger, the paper does not get written.',
  why:'"Electronics" is not a category - the job is. Tonight that charger\u2019s job is school, which makes it a Need, and $35 of flexible money covers it cleanly.'},
]},
'available-money':{intro:'The number on the screen is not the number you can spend.',steps:[
 {t:'teach',h:'The number on the screen lies a little',
  body:'<p>Your app shows a <b>balance</b>. But some of that money already has a job:</p><ul><li><b>Scheduled payments</b> - autopay that has not hit yet.</li><li><b>Pending charges</b> - swiped but not posted.</li><li><b>Promises</b> - money you already decided to save.</li></ul><p><b>Available money = balance \u2212 money that already has a job.</b> Spend from the available number, never the visible one.</p>'},
 {t:'example',h:'Maya checks before she spends',story:'<p>Friday night. Maya\u2019s app shows <b>$320</b>. A friend invites her to dinner - about $40. She checks first:</p>',
  points:['Balance on screen: $320','Electric autopay hits tomorrow: \u2212$90','Promised to emergency savings: \u2212$40','Actually available: <b>$190</b>','Dinner fits. She goes - and the electric bill is safe.']},
 {t:'try',q:'Your app shows $200. A $60 rent autopay hits tomorrow. Nothing else is pending. What is actually available?',
  choices:[{label:'$200',ok:false},{label:'$140',ok:true},{label:'$140 now, then $200 again after the autopay hits',ok:false},{label:'$260',ok:false}],
  hint:'Subtract the money that already has a job.',
  good:'Right: $200 \u2212 $60 = $140.',
  bad:'Subtract the scheduled $60 first: $200 \u2212 $60 = $140.',
  why:'The $60 is already spoken for. Available = $200 \u2212 $60 = $140.'},
 {t:'try',q:'App shows $500. $200 rent autopay in 3 days, a $45 pending gas hold, and $50 you promised to savings. Available?',
  choices:[{label:'$500',ok:false},{label:'$250 - pending holds do not count until they post',ok:false},{label:'$255',ok:false},{label:'$205',ok:true}],
  hint:'Three things already have a job. Subtract all three.',
  good:'Right: $500 \u2212 $200 \u2212 $45 \u2212 $50 = $205.',
  bad:'Count everything with a job: $200 + $45 + $50 = $295 spoken for. $500 \u2212 $295 = $205.',
  why:'Rent, the pending hold, and the savings promise all count. $500 \u2212 $295 = $205 actually available.'},
 {t:'try',q:'It is Wednesday. Maya\u2019s balance is $150. A $100 paycheck lands Friday; $90 rent autopay hits Saturday. What is the most she can spend today without risking the rent?',
  choices:[{label:'$150 - the whole visible balance',ok:false},{label:'$60 - the balance minus the rent, without counting Friday\u2019s pay',ok:true},{label:'$160 - count Friday\u2019s paycheck too',ok:false},{label:'$10 - keep everything, just in case',ok:false}],
  hint:'Which of those future numbers is guaranteed today?',
  good:'Right: $150 \u2212 $90 = $60. Friday\u2019s money does not exist yet.',
  bad:'Protect the scheduled rent from today\u2019s balance - and do not spend a paycheck that has not landed.',
  why:'Two rules in one: subtract scheduled costs from what you have <i>now</i> ($150 \u2212 $90 = $60), and never spend income before it arrives. Friday\u2019s $100 is a hope until it posts.'},
 {t:'try',q:'Maya\u2019s app still shows yesterday\u2019s $220 balance, but she spent $35 on groceries this morning and the charge is pending. What is actually available?',
  choices:[{label:'$220 - pending is not real until it posts',ok:false},{label:'$185',ok:true},{label:'$255 - pending charges get added back',ok:false},{label:'Impossible to know until the charge posts',ok:false}],
  hint:'The money is already spoken for, posted or not.',
  good:'Right: $220 \u2212 $35 = $185.',
  bad:'Pending still means spent. $220 \u2212 $35 = $185.',
  why:'"Posted" is a bank technicality, not a money fact. The $35 already has a job - groceries - so available is $185 whether the app has caught up or not.'},
 {t:'tool',screen:'home',h:'See it on a dashboard',body:'<p>The home dashboard separates <b>Available now</b>, <b>Known Needs</b>, and <b>Flexible after known costs</b> - the same check you just did, live.</p>',cta:'Open the dashboard'}
]},
'depends-decisions':{intro:'Context changes the category. "It depends" is a real answer.',steps:[
 {t:'teach',h:'"It depends" is a real answer',
  body:'<p>The same item can be a Need for one person and a Want for another. The category is not in the <i>thing</i> - it is in the <b>context</b>.</p><p>When you are unsure, ask: <b>"What is it for, right now?"</b></p><ul><li>Winter coat, October, you own none \u2192 Need.</li><li>Winter coat, you already own a warm one \u2192 Want.</li><li>Laptop, required for classes \u2192 Need.</li><li>Laptop, mostly for games \u2192 Want.</li></ul>'},
 {t:'sort',h:'Sort it: context matters',body:'<p>Each item comes with its context. Some are clear. Two of them genuinely depend - use the <b>It depends</b> bucket.</p>',
  buckets:['Need','Want','It depends'],
  items:[
   {label:'Laptop - required for your classes',a:'need',why:'Required to function as a student. Need.'},
   {label:'Laptop - mostly for gaming',a:'want',why:'Same object, different job. For games it is a Want.'},
   {label:'Winter coat - it is October and you own none',a:'need',why:'Health and safety. Need.'},
   {label:'Winter coat - you already own a warm one',a:'want',why:'The second coat is optional. Want.'},
   {label:'Car - no bus route to your job',a:'need',why:'Without it there is no income. Need.'},
   {label:'Car - just for weekend fun',a:'want',why:'Fun is a Want - a great one, but a Want.'},
   {label:'Ordering takeout (no other info)',a:'depends',why:'Depends: no food at home leans Need; a craving leans Want. You need more info.'},
   {label:'A $60 video game (no other info)',a:'depends',why:'Depends: a gift for a friend? a reward you planned? Without context you cannot sort it.'}]},
 {t:'try',q:'Two students buy the same $120 shoes. One\u2019s old shoes have holes; the other\u2019s are fine. Who made a Need purchase?',
  choices:[{label:'The one whose shoes had holes',ok:true},{label:'The one who paid less for them',ok:false},{label:'Both - same shoes, same category',ok:false},{label:'Neither - shoes are always Wants',ok:false}],
  hint:'Same item, different context.',
  good:'Exactly. The category lives in the context, not the price tag.',
  bad:'Look at the context, not the item. Holes = function = Need.',
  why:'Identical purchase, different categories. This is why "what is it for, right now?" beats any fixed list.'},
 {t:'try',q:'Maya has $40. She needs $30 for groceries and wants a $15 game. She cannot do both. What does the routine say?',
  choices:[{label:'Buy the game now, figure out groceries later',ok:false},{label:'Skip groceries - the game is on sale and will not wait',ok:false},{label:'Protect the $30 need first; the game waits',ok:true},{label:'Split it: $20 groceries, $15 game, hope for the best',ok:false}],
  hint:'Remember the order: Needs first, then Savings, then Wants.',
  good:'Right. Needs are protected first. The Want waits for "what is left."',
  bad:'The routine protects Needs before Wants. Groceries first.',
  why:'When money is short, the routine is a tiebreaker: Needs win. The game is a fine Want - next week, from what is left.'},
 {t:'try',q:'Maya\u2019s friend says "a car is always a Need - every adult needs one." What is the best answer?',
  choices:[{label:'Agree - transportation is always a Need',ok:false},{label:'Disagree - it depends on her job, bus routes, and alternatives',ok:true},{label:'Agree - expensive things are Needs',ok:false},{label:'Disagree - cars are always Wants',ok:false}],
  hint:'Fixed lists, or context?',
  good:'Exactly. No item is automatically anything.',
  bad:'"Always" is the giveaway. The category lives in the context.',
  why:'A car with no bus route to work is a Need; the same car for weekend fun is a Want. Fixed lists break - "what is it for, right now?" does not.'},
 {t:'try',q:'Maya has groceries at home. Coworkers invite her to a $14 lunch. How should she sort the lunch?',
  choices:[{label:'Need - food is always a Need',ok:false},{label:'Want - she has food at home, so this lunch is social and optional',ok:true},{label:'It depends - this one is impossible to sort',ok:false},{label:'Savings - skipping it saves $14',ok:false}],
  hint:'She already has food. What is the lunch really for?',
  good:'Right. The food need is covered; the lunch is a social Want.',
  bad:'Food at home covers the Need. This $14 is buying company, not calories.',
  why:'"Food is a Need" is true - and already handled by her groceries. The lunch\u2019s real job is social, which makes it a Want. (And "skipping it saves $14" confuses not-spending with the Savings bucket.)'},
]}
};

/* ================= MODULE 2: Make Money Last ================= */
Object.assign(LESSON_CONTENT,{
'pacing-basics':{intro:'Turn a lump of money into a weekly pace you can actually follow.',steps:[
 {t:'teach',h:'Divide money by time',
  body:'<p>A month of money feels huge on day one and tiny on day twenty. <b>Pacing</b> fixes that:</p><p><b>Flexible money \u00f7 time remaining = your pace.</b></p><p>The pace is a <i>speed limit</i>, not a target. Staying under it means the money lasts. Use <i>flexible</i> money - after Needs and Savings are protected - never the full balance.</p>'},
 {t:'example',h:'Maya paces $400',story:'<p>Maya has $400 for 4 weeks. She protects $200 for needs and savings first, leaving $200 flexible.</p>',
  points:['Flexible money: $200','Time: 4 weeks','Pace: $200 \u00f7 4 = <b>$50/week</b>','Week 2, she has spent $45. She is under pace - the money will last.']},
 {t:'try',q:'You have $300 of flexible money and 3 weeks left. What is your weekly pace?',
  choices:[{label:'$100/week',ok:true},{label:'$150/week',ok:false},{label:'No pace needed - $300 is small enough to just spend',ok:false},{label:'$300/week',ok:false}],
  hint:'Flexible money \u00f7 time.',
  good:'Right: $300 \u00f7 3 = $100/week.',
  bad:'Divide the flexible money by the weeks: $300 \u00f7 3 = $100/week.',
  why:'Pace = $300 \u00f7 3 weeks = $100/week. Spend at or under it and the money lasts.'},
 {t:'try',q:'You had $400 for 4 weeks - a $100/week pace. But you spent $130 in week 1. What is the new pace for the remaining $270 over 3 weeks?',
  choices:[{label:'$100/week - stick to the original plan',ok:false},{label:'$110/week - the plan is already blown, so it does not matter',ok:false},{label:'$90/week',ok:true},{label:'$67.50/week',ok:false}],
  hint:'Forget the original plan. Use what REMAINS.',
  good:'Right: $270 \u00f7 3 = $90/week. You recalculated from what remains.',
  bad:'Do not punish yourself or cling to the old plan. $270 \u00f7 3 = $90/week.',
  why:'Overspending does not mean the plan failed - it means the plan updates. New pace = remaining money \u00f7 remaining time = $270 \u00f7 3 = $90/week.'},
 {t:'try',q:'Payday: $1,800 for the month. Needs: $1,050. Savings: $150. What is the daily pace for flexible spending?',
  choices:[{label:'$60/day',ok:false},{label:'$20/day',ok:true},{label:'$50/day - round the needs down to keep it simple',ok:false},{label:'$35/day',ok:false}],
  hint:'Flexible first, then divide by 30.',
  good:'Right: ($1,800 \u2212 $1,050 \u2212 $150) = $600 \u00f7 30 = $20/day.',
  bad:'Protect Needs and Savings first: $1,800 \u2212 $1,050 \u2212 $150 = $600. Then $600 \u00f7 30 = $20/day.',
  why:'$60/day would spend the rent money. The pace only ever applies to flexible money: $600 \u00f7 30 = $20/day.'},
 {t:'try',q:'Maya\u2019s pace is $50/week on $200 for 4 weeks. She spends $45 in week 1, $50 in week 2, and only $30 in week 3. What is week 4\u2019s pace?',
  choices:[{label:'$75 - the unspent money rolls into the new pace',ok:true},{label:'$50 - the pace never changes',ok:false},{label:'$20 - bank the surplus as extra savings',ok:false},{label:'$95 - reward weeks under pace with a bigger week',ok:false}],
  hint:'Recalculate from what remains - in both directions.',
  good:'Right: $200 \u2212 $125 = $75 left for 1 week.',
  bad:'$200 \u2212 $45 \u2212 $50 \u2212 $30 = $75 remains. One week left: $75.',
  why:'Pace recalculates from what remains - under-spending raises it, over-spending lowers it. The plan updates from reality, never from the original number.'},
 {t:'tool',screen:'pacing-value',focus:'pacing',h:'Try the pacing calculator',body:'<p>Enter your own numbers and watch the pace compute - including what happens when you change the time left.</p>',cta:'Open the pacing calculator'}
]},
'safe-to-spend':{intro:'Balance is what exists. Safe to spend is what is left after money with a job.',steps:[
 {t:'teach',h:'Two different numbers',
  body:'<p><b>Balance</b> = everything in the account.<br><b>Safe to spend</b> = balance \u2212 future needs \u2212 protected savings.</p><p>Confusing the two is the #1 way people "mysteriously" run out of money. The balance includes money that already has a job.</p>'},
 {t:'example',h:'Maya\u2019s two numbers',story:'<p>Maya\u2019s balance: <b>$400</b>.</p>',
  points:['Future transport this month: \u2212$120','Protected savings: \u2212$80','Safe to spend: <b>$200</b>','Over 4 weeks: $50/week safe. The $400 balance would have lied to her.']},
 {t:'try',q:'Balance $400. Transport $120 coming up. Savings $80 protected. What is safe to spend per week over 4 weeks?',
  choices:[{label:'$100/week',ok:false},{label:'$70/week - savings can cover any shortfall',ok:false},{label:'$50/week',ok:true},{label:'$400 - it is all there',ok:false}],
  hint:'Balance minus the money with a job, then divide.',
  good:'Right: ($400 \u2212 $120 \u2212 $80) \u00f7 4 = $50/week.',
  bad:'First find safe to spend: $400 \u2212 $120 \u2212 $80 = $200. Then $200 \u00f7 4 = $50/week.',
  why:'$400 is the balance; $200 is safe to spend. Spending from the balance spends the transport and savings money too.'},
 {t:'try',q:'Your friend says "I have $800, I\u2019m set this month!" But $500 rent + $150 bills hit before next payday. What is actually safe?',
  choices:[{label:'$800 - it is all available',ok:false},{label:'$300 - rent is not due yet, so it does not count',ok:false},{label:'$150',ok:true},{label:'$650',ok:false}],
  hint:'Subtract every future need first.',
  good:'Right: $800 \u2212 $500 \u2212 $150 = $150.',
  bad:'The rent and bills already have a job: $800 \u2212 $650 = $150 safe.',
  why:'Feeling rich from the balance is the trap. $650 is spoken for; $150 is the real number to plan around.'},
 {t:'try',q:'Maya is paid $900. Before spending anything, $400 rent, $120 bills, and $100 savings are spoken for. A friend says "you\u2019ve got $900 to spend!" What is actually safe to spend?',
  choices:[{label:'$900 - it is all in her account',ok:false},{label:'$280',ok:true},{label:'$380 - savings is still her money',ok:false},{label:'$500 - the bills are not due yet',ok:false}],
  hint:'Subtract everything with a job - including the savings promise.',
  good:'Right: $900 \u2212 $400 \u2212 $120 \u2212 $100 = $280.',
  bad:'$900 \u2212 $400 (rent) \u2212 $120 (bills) \u2212 $100 (savings) = $280.',
  why:'"Savings is still my money" is the sneakiest trap here: the moment savings is spent, it stops being savings. Safe to spend is $280.'},
 {t:'try',q:'What is the #1 cause of "mysteriously" running out of money before payday?',
  choices:[{label:'Spending from the balance instead of the safe-to-spend number',ok:true},{label:'Checking the banking app too often',ok:false},{label:'Using cash instead of a card',ok:false},{label:'Paying bills a few days early',ok:false}],
  hint:'Which number lies a little?',
  good:'Exactly. The balance includes money that already has a job.',
  bad:'The balance is the liar: it shows money already promised to rent, bills, and savings.',
  why:'Almost every "where did it go?" story is balance-spending: the account showed $800, but $650 already had jobs. Plan from safe-to-spend and the mystery disappears.'},
]},
'savings-purpose':{intro:'Savings is not a vault you never open. It is money with a future job.',steps:[
 {t:'teach',h:'Savings has a job description',
  body:'<p>"Savings" is vague, and vague money gets spent. Give it a job:</p><ul><li><b>Emergency money</b> - for surprises (car repair, medical).</li><li><b>Planned goal</b> - textbooks, a deposit, a trip.</li><li><b>Future need</b> - tuition due in 3 months.</li></ul><p>When the job arrives, <b>using the savings IS the plan working</b> - not a failure.</p>'},
 {t:'example',h:'Maya\u2019s textbooks',story:'<p>Maya saved $180 for textbooks all semester.</p>',
  points:['Saved: $180 (job: textbooks)','Books cost: $165','She spends the $165 from savings - the plan worked.','$15 stays saved for next time.']},
 {t:'try',q:'Maya saved $180 for textbooks. The books cost $165 and she buys them from savings. What happened?',
  choices:[{label:'She failed - savings should never be touched',ok:false},{label:'The savings did its job',ok:true},{label:'She oversaved - the $15 leftover proves the goal was too high',ok:false},{label:'She should feel guilty',ok:false}],
  hint:'What was the money\u2019s job?',
  good:'Exactly. That is what the money was for.',
  bad:'The money\u2019s job was textbooks. Using it for textbooks is success.',
  why:'Savings with a purpose is meant to be spent <i>on its purpose</i>. Untouched savings with no job is just unspent money.'},
 {t:'try',q:'Maya has $200 in emergency savings and a $200 surprise car repair. She also wants $80 concert tickets. What should the emergency money do?',
  choices:[{label:'Cover the repair - that is its job',ok:true},{label:'Put the repair on a credit card and keep the $200 saved',ok:false},{label:'Buy the concert tickets - emergencies can wait',ok:false},{label:'Split it: half repair, half concert',ok:false}],
  hint:'Match the money to its job description.',
  good:'Right. The repair is exactly what emergency money exists for.',
  bad:'Emergency money has one job: emergencies. The concert is a Want.',
  why:'Purpose beats impulse. The repair is the emergency the fund was built for; the concert waits for flexible money.'},
 {t:'try',q:'Maya\u2019s emergency fund reaches her $500 goal. She keeps auto-moving $40/month into it out of habit. Smart?',
  choices:[{label:'Yes - you can never have too much emergency money',ok:false},{label:'It did its job - now redirect that $40 to the next goal',ok:true},{label:'No - she should spend the $500 to celebrate',ok:false},{label:'No - emergency money should go into stocks instead',ok:false}],
  hint:'What was the fund\u2019s job description?',
  good:'Right. A funded goal frees the money for its next assignment.',
  bad:'The job was "$500 of emergency buffer." Done - give the $40 its next job.',
  why:'Endless emergency saving has an opportunity cost: that $40 could be building the next goal. Fund the job, then reassign the worker.'},
 {t:'try',q:'Maya uses emergency savings for concert tickets, planning to "pay it back next month." What is the real risk?',
  choices:[{label:'No risk - paying it back makes it completely fine',ok:false},{label:'The payback rarely happens, and the fund loses its job',ok:true},{label:'The bank charges a fee for touching savings',ok:false},{label:'Concerts are never worth any money',ok:false}],
  hint:'How often do "I\u2019ll pay it back" plans survive contact with next month?',
  good:'Exactly. Borrowed-from-self is still spent.',
  bad:'Next month has its own plans. The payback loses to them almost every time.',
  why:'"Pay it back" turns the emergency fund into a loan desk with a borrower who never signs paperwork. The fund\u2019s job was emergencies - concert tickets rewrite the job description.'},
]},
'irregular-income':{intro:'Do not budget money that has not arrived yet.',steps:[
 {t:'teach',h:'Irregular income needs a stricter rule',
  body:'<p>When shifts vary, the paycheck is a <i>guess</i> until it lands. The rule:</p><ol><li><b>Protect required costs first</b> - what MUST be paid before the next known income.</li><li><b>Hold a buffer</b> - a cushion for the gap.</li><li><b>Only then</b> treat the rest as flexible.</li></ol><p>Never spend "expected" shifts. Budget the cash in hand.</p>'},
 {t:'example',h:'Maya\u2019s slow weeks',story:'<p>Two slow weeks ahead. Maya has $300 cash, $170 in required costs, and no guaranteed shifts.</p>',
  points:['Cash in hand: $300','Required costs: \u2212$170','Buffer for the gap: \u2212$50','Flexible: <b>$80</b>. Small - and honest.']},
 {t:'try',q:'You have $300 cash, $170 in required costs before any more known income, and no guaranteed shifts. A $50 buffer is wise. What is flexible?',
  choices:[{label:'$300 - all of it',ok:false},{label:'$130 - buffers are only for people with steady jobs',ok:false},{label:'$130',ok:false},{label:'$80',ok:true}],
  hint:'Protect, buffer, then see what is left.',
  good:'Right: $300 \u2212 $170 \u2212 $50 = $80.',
  bad:'$300 \u2212 $170 (required) \u2212 $50 (buffer) = $80 flexible.',
  why:'With irregular income, required costs and a buffer come off the top. Only $80 is truly flexible.'},
 {t:'try',q:'Your friend has $250 cash, $180 in bills due, and no shifts scheduled. He says "just spend normally - you\u2019ll pick up shifts." What is the flaw?',
  choices:[{label:'There is no flaw - optimism pays bills',ok:false},{label:'He is budgeting shifts that do not exist yet',ok:true},{label:'He should skip the bills this month to keep spending normally',ok:false},{label:'He should spend faster before the money disappears',ok:false}],
  hint:'What is he counting that is not in his hand?',
  good:'Exactly. Expected income is not income.',
  bad:'He is spending money from shifts he has not worked. Protect first.',
  why:'"You will pick up shifts" is a hope, not a paycheck. The rule: budget cash in hand, protect required costs, hold a buffer.'},
 {t:'try',q:'Maya\u2019s gig pay was $1,200 last month and $600 the month before. She is eyeing a $90/month subscription. How should she decide?',
  choices:[{label:'Use the $1,200 month - that is her real earning power',ok:false},{label:'Plan from the $600 month - the low end is the honest number',ok:true},{label:'Average them: $900/month, so $90 is fine',ok:false},{label:'$90 is small - just get it',ok:false}],
  hint:'Which month has to cover the bill when work dries up?',
  good:'Right. If the $600 month cannot carry it, the subscription owns her.',
  bad:'Averages lie when income swings: the $600 month is the one that must pay the bill.',
  why:'Recurring costs must survive the worst normal month, not the best one. Plan from the low end; let good months build the buffer.'},
 {t:'try',q:'Big week: Maya earns $400 from gigs. Required costs before the next income: $250. She feels rich. What is the move?',
  choices:[{label:'Spend the $150 freely - great weeks are for enjoying',ok:false},{label:'Protect the $250, hold a buffer, treat only the rest as flexible',ok:true},{label:'Save all $400 - great weeks should be saved entirely',ok:false},{label:'Lend $100 to a friend - she clearly has extra',ok:false}],
  hint:'Feeling rich is a feeling. What are the numbers?',
  good:'Right. The routine does not take weeks off.',
  bad:'$400 \u2212 $250 required \u2212 buffer = a small flexible number, not $150 of fun.',
  why:'"Feeling rich" after one good week is how irregular earners go broke: the $250 of required costs did not get the memo. Protect, buffer, then enjoy what is actually left.'},
 {t:'tool',screen:'pacing-value',focus:'irregular',h:'Try the irregular-income calculator',body:'<p>Plug in cash on hand, required costs, and a buffer - see what is honestly flexible.</p>',cta:'Open the calculator'}
]},
'semester-plan':{intro:'Lump sums lie. Break them into periods.',steps:[
 {t:'teach',h:'Big money, long time',
  body:'<p>A semester refund, a tax refund, a bonus - lump sums <i>feel</i> huge on day one. The fix is the same pace math, stretched out:</p><p><b>(Lump sum \u2212 needs \u2212 savings) \u00f7 number of periods = pace per period.</b></p><p>A $3,200 semester refund is not $3,200 of spending money. It is 16 weeks of paced money.</p>'},
 {t:'example',h:'Maya\u2019s semester refund',story:'<p>$3,200 refund lands in August. Semester is 16 weeks.</p>',
  points:['Semester needs: \u2212$1,600','Savings goal: \u2212$400','Flexible: $1,200','Pace: $1,200 \u00f7 16 = <b>$75/week</b> for the whole semester.']},
 {t:'try',q:'$3,200 for the semester. $1,600 in needs, $400 savings goal, 16 weeks. What is the weekly pace?',
  choices:[{label:'$200/week',ok:false},{label:'$150/week for the first 8 weeks, then figure out the rest',ok:false},{label:'$75/week',ok:true},{label:'$3,200 - spend as needed',ok:false}],
  hint:'Flexible money \u00f7 weeks.',
  good:'Right: ($3,200 \u2212 $1,600 \u2212 $400) \u00f7 16 = $75/week.',
  bad:'Protect first: $3,200 \u2212 $2,000 = $1,200 flexible. $1,200 \u00f7 16 = $75/week.',
  why:'$200/week would burn through the needs money by October. $75/week lasts all 16 weeks.'},
 {t:'try',q:'You get a $1,000 tax refund. Rent is $600/month. Your friend says "we\u2019re set for months!" What is wrong?',
  choices:[{label:'Nothing - $1,000 is a lot',ok:false},{label:'It covers less than 2 months of rent - it is one-time money against ongoing costs',ok:true},{label:'Nothing - refunds come every year, so it is basically recurring income',ok:false},{label:'Refunds do not count as money',ok:false}],
  hint:'One-time money \u00f7 ongoing costs.',
  good:'Exactly. $1,000 \u00f7 $600 = about 1.6 months. Then what?',
  bad:'Divide: $1,000 covers rent for ~1.6 months. "Set for months" is the lump-sum illusion.',
  why:'Lump sums feel permanent; they are not. Always divide one-time money by the ongoing cost to see how long it really lasts.'},
 {t:'try',q:'Two students each get a $2,000 semester refund. Ana paces it at $125/week for 16 weeks. Ben spends $500 in week 1 "getting set up." Who is more likely to have money in week 12?',
  choices:[{label:'Ana - the pace protects every week equally',ok:true},{label:'Ben - spending early on setup saves money later',ok:false},{label:'Neither - refunds never last the semester',ok:false},{label:'Ben - $500 of setup is always worth it',ok:false}],
  hint:'Week 1 spending does not buy week 12 groceries.',
  good:'Right. Ana\u2019s money has a plan for week 12; Ben\u2019s does not.',
  bad:'Ben\u2019s $500 is gone by week 2. Ana still has $125/week arriving on schedule.',
  why:'"Getting set up" feels productive, but money spent in week 1 cannot cover week 12. Pacing is time-travel for dollars: Ana sent hers forward.'},
 {t:'try',q:'Maya\u2019s refund leaves $1,200 flexible over 16 weeks - a $75/week pace. Her friend says "$400/month is fine, monthly math is easier." What is wrong?',
  choices:[{label:'Nothing - monthly math is simpler and close enough',ok:false},{label:'16 weeks is not 4 months - $400/month overshoots the $75/week pace',ok:true},{label:'$400/month is too low - she can afford more',ok:false},{label:'Weekly pacing does not apply to refunds',ok:false}],
  hint:'How many weeks are in the average month?',
  good:'Right: $75/week \u00d7 4.33 is about $325/month, not $400.',
  bad:'A month averages 4.33 weeks. $400/month over 3.7 months = $1,480 - $280 over budget.',
  why:'"Monthly math is easier" quietly adds phantom weeks: 16 weeks is 3.7 months, not 4. $400/month spends $1,480 of a $1,200 plan. Pace in weeks when the money must last weeks.'},
 {t:'tool',screen:'plan',h:'Try the semester planner',body:'<p>Map a lump sum across a whole semester and watch the weekly pace appear.</p>',cta:'Open the planner'}
]}
});

/* ================= MODULE 3: Spend Smart ================= */
Object.assign(LESSON_CONTENT,{
'sales-decisions':{intro:'A discount is not savings if it causes a purchase you would not make.',steps:[
 {t:'teach',h:'The "was I going to buy it anyway" test',
  body:'<p>Sales are designed to make spending feel like saving. Cut through it with one question:</p><p><b>"Was I already going to buy this?"</b></p><ul><li><b>Yes</b> \u2192 the discount is real savings. Take it.</li><li><b>No</b> \u2192 you did not save anything. You spent money you were not going to spend.</li></ul><p>"50% off" on something you did not want is not a deal. It is 50% off <i>still spending</i>.</p>'},
 {t:'example',h:'Maya faces two sales',story:'<p>Sale 1: Maya needs shampoo ($8). It is buy-one-get-one 50% off. She buys two for $12 - she will use both.</p><p>Sale 2: $40 shoes, 50% off ($20). She did not need shoes.</p>',
  points:['Sale 1: needed it anyway \u2192 real savings of $4.','Sale 2: did not need them \u2192 she "saved" $20 by spending $20.','Same 50% off. Opposite results. The test tells them apart.']},
 {t:'try',q:'Maya was not going to buy a $60 jacket. It is 50% off, so $30, and she buys it. Did she save $30?',
  choices:[{label:'Yes - half price is half price',ok:false},{label:'Yes - $30 is objectively cheap for a jacket',ok:false},{label:'No - she spent $30 she was not going to spend',ok:true},{label:'Yes - as long as she wears it a lot, it becomes savings',ok:false}],
  hint:'Was she going to buy it anyway?',
  good:'Right. No planned purchase = no savings.',
  bad:'Apply the test: she was NOT going to buy it. So she saved nothing.',
  why:'Savings require a planned purchase. Without one, "50% off" just means spending $30 instead of $0.'},
 {t:'try',q:'A store offers $20 off any $100 purchase. Maya adds a $25 item she does not need to reach $100. Good deal?',
  choices:[{label:'Yes - she got $20 off',ok:false},{label:'No - she spent $25 extra to "save" $20',ok:true},{label:'Yes - she can return the $25 item later and keep the $20 off',ok:false},{label:'Yes - free shipping makes it worth it',ok:false}],
  hint:'Do the net math.',
  good:'Right: \u2212$25 + $20 = \u2212$5. She lost $5.',
  bad:'Net it out: she spent $25 to save $20. That is \u2212$5.',
  why:'Threshold deals ("spend $X, save $Y") bait you into adding unneeded items. Net math: \u2212$25 spent + $20 saved = $5 lost.'},
 {t:'try',q:'"Buy 2, get 1 free" on $10 shampoo - 3 bottles for $20. Maya uses one bottle every 2 months and it does not expire. Deal?',
  choices:[{label:'Yes - free is free, always take it',ok:false},{label:'Yes - she will use all three within 6 months, so the discount is real',ok:true},{label:'No - bulk deals are always a trap',ok:false},{label:'Only if she splits it with a friend',ok:false}],
  hint:'Was she going to buy it anyway - all three of them?',
  good:'Right. Planned purchase plus no waste: real savings of $10.',
  bad:'She buys shampoo anyway and uses it before it expires - the test passes.',
  why:'This is the sale done right: she was going to buy shampoo regardless, and all three bottles get used. "Was I going to buy it anyway?" and "will I use it?" both say yes.'},
 {t:'try',q:'A 70%-off "limited time" sale ends tonight on a $200 item Maya has never considered. She feels urgent. What should she do?',
  choices:[{label:'Buy now - 70% off never comes back',ok:false},{label:'Run the test: she was not going to buy it, so the urgency is the tactic',ok:true},{label:'Wait for an 80%-off sale',ok:false},{label:'Buy it - returns are easy if she changes her mind',ok:false}],
  hint:'Who benefits from the urgency - her or the store?',
  good:'Right. The countdown clock is doing the selling, not the discount.',
  bad:'"Limited time" manufactures the feeling of missing out. The test cuts through it.',
  why:'Urgency is a sales tool, not information. If she was not going to buy it at full price, 70% off a $0 plan is still $60 of unplanned spending.'},
]},
'usable-value':{intro:'Compare what you will USE, not what is in the package.',steps:[
 {t:'teach',h:'Unit price is only half the story',
  body:'<p><b>Unit price = price \u00f7 quantity.</b> But the quantity that matters is what you will <i>actually use</i>:</p><p><b>True unit price = price \u00f7 units you will use.</b></p><p>A giant pack is only cheaper if the extra does not go in the trash. Waste is the most expensive ingredient.</p>'},
 {t:'example',h:'Maya compares two packs',story:'<p>Pasta: 12-pack for $9 ($0.75 each) vs 6-pack for $5.40 ($0.90 each).</p>',
  points:['She will use all 12 before they expire.','True cost: $0.75 vs $0.90 per pack.','The 12-pack wins - <i>because none is wasted</i>.']},
 {t:'try',q:'12-pack for $9 ($0.75 each) vs 6-pack for $5.40 ($0.90 each). Maya will use all 12. Which is the better buy?',
  choices:[{label:'The 12-pack',ok:true},{label:'The 6-pack - $5.40 total is less than $9',ok:false},{label:'The 6-pack - smaller is safer',ok:false},{label:'Neither - $0.75 and $0.90 are basically the same',ok:false}],
  hint:'Compare true unit prices.',
  good:'Right: $0.75 < $0.90 per pack used.',
  bad:'$9 \u00f7 12 = $0.75 each vs $5.40 \u00f7 6 = $0.90 each. The 12-pack is cheaper per use.',
  why:'When everything gets used, the lower unit price wins: $0.75 vs $0.90 per pack.'},
 {t:'try',q:'Same two packs - but Maya will only use 6 before they expire. Now which is better?',
  choices:[{label:'Still the 12-pack - the sticker says $0.75',ok:false},{label:'The 12-pack - she can sell the extra 6 to a friend',ok:false},{label:'The 6-pack',ok:true},{label:'They tie - both give her the 6 packs she needs',ok:false}],
  hint:'Recompute with 6 used, not 12 bought.',
  good:'Right: $9 \u00f7 6 used = $1.50 each vs $0.90. The 6-pack wins.',
  bad:'True unit price uses what you USE: $9 \u00f7 6 = $1.50 each. The 6-pack at $0.90 wins.',
  why:'Waste flips the answer. $9 for 6 used = $1.50 each - nearly double the 6-pack. Always divide by what you will use.'},
 {t:'try',q:'Laundry detergent: $12 for 60 loads vs $9 for 40 loads. Maya will use every drop. Which is the better buy?',
  choices:[{label:'The $12 jug - $0.20/load beats $0.225/load',ok:true},{label:'The $9 jug - the lower total is cheaper',ok:false},{label:'They are the same - both wash clothes',ok:false},{label:'The bigger jug - bigger is always the better value',ok:false}],
  hint:'Divide price by loads you will use.',
  good:'Right: $12 \u00f7 60 = $0.20 vs $9 \u00f7 40 = $0.225.',
  bad:'$0.20/load is less than $0.225/load. When all of it gets used, unit price decides.',
  why:'"Lower total" and "bigger is better" are both shortcuts that skip the division. True unit price - price \u00f7 loads you will use - is the whole answer.'},
 {t:'try',q:'Granola bars: 30-pack for $15 ($0.50 each) vs 6-pack for $4.50 ($0.75 each). Maya\u2019s family will eat 10 before the rest expire. Now which wins?',
  choices:[{label:'The 6-pack - $15 \u00f7 10 eaten = $1.50 per bar vs $0.75',ok:true},{label:'The 30-pack - the sticker says $0.50 each',ok:false},{label:'The 30-pack - she can donate the rest before they expire',ok:false},{label:'Neither - granola bars are a Want, so value does not matter',ok:false}],
  hint:'Divide by bars eaten, not bars bought.',
  good:'Right: $15 \u00f7 10 = $1.50 per bar actually eaten.',
  bad:'True unit price uses what gets used: $15 \u00f7 10 = $1.50 each. The 6-pack at $0.75 wins.',
  why:'The sticker\u2019s $0.50 assumes all 30 get eaten. Waste rewrites the price: $1.50 per bar eaten is double the small pack. "Donate the rest" changes the question instead of answering it.'},
 {t:'tool',screen:'pacing-value',focus:'value',h:'Try the value calculator',body:'<p>Compare packs with unit price - and factor in what you will actually use.</p>',cta:'Open the value calculator'}
]},
'gas-value':{intro:'Count the cost of getting the deal.',steps:[
 {t:'teach',h:'The pump price is not the full price',
  body:'<p>Driving for cheaper gas has a cost: the trip itself.</p><p><b>Real savings = pump savings \u2212 extra trip cost.</b></p><p>Extra trip cost = (extra miles \u00f7 mpg) \u00d7 gas price. If the station is <i>on your route anyway</i>, the extra cost is $0 - then the cheaper pump always wins.</p>'},
 {t:'example',h:'Maya does the math',story:'<p>Station A: $3.00/gal, next door. Station B: $2.85/gal, 8 extra miles round trip. 12 gallons, 25 mpg.</p>',
  points:['Pump savings: 12 \u00d7 $0.15 = $1.80','Trip cost: (8 \u00f7 25) \u00d7 $3.00 \u2248 $0.96','Real savings: $1.80 \u2212 $0.96 = <b>$0.84</b>','Worth it? Barely. A smaller gap would flip it.']},
 {t:'try',q:'12 gallons. Station B is $0.15 cheaper but 8 extra miles round trip (25 mpg, gas $3.00). What is the right comparison?',
  choices:[{label:'Just the pump price - $0.15 cheaper wins',ok:false},{label:'Pump savings minus the extra trip cost',ok:true},{label:'The one with cheaper snacks - you are stopping anyway',ok:false},{label:'Always pick the closest station',ok:false}],
  hint:'What does the trip itself cost?',
  good:'Right: $1.80 pump savings \u2212 ~$0.96 trip cost = ~$0.84 real savings.',
  bad:'Subtract the trip: (8 \u00f7 25) \u00d7 $3.00 \u2248 $0.96. $1.80 \u2212 $0.96 = $0.84.',
  why:'The pump price ignores the drive. Real savings = $1.80 \u2212 $0.96 \u2248 $0.84.'},
 {t:'try',q:'The cheaper station is directly on Maya\u2019s normal route to work - zero extra miles. Which station wins?',
  choices:[{label:'The cheaper one - no extra trip cost',ok:true},{label:'The more expensive one - cheap gas damages engines',ok:false},{label:'The closer one - habit beats math',ok:false},{label:'It does not matter - $0.15 a gallon is too small to count',ok:false}],
  hint:'What is the extra trip cost now?',
  good:'Right. Zero extra miles = zero extra cost. Cheaper pump wins outright.',
  bad:'Extra miles = 0, so extra cost = $0. The cheaper pump wins with no penalty.',
  why:'On-route changes everything: the trip cost drops to $0, so the full $1.80 pump savings is real.'},
 {t:'try',q:'Maya needs 10 gallons. Station X: $3.20, on her route. Station Y: $3.05, 6 extra miles round trip. Her car gets 30 mpg. Which wins?',
  choices:[{label:'Y - $1.50 pump savings minus about $0.64 in trip cost = about $0.86 real savings',ok:true},{label:'X - a detour always wipes out the savings',ok:false},{label:'Y - the pump price is the only number that matters',ok:false},{label:'X - 6 miles is too far for any discount',ok:false}],
  hint:'Pump savings minus trip cost.',
  good:'Right: 10 \u00d7 $0.15 = $1.50; (6 \u00f7 30) \u00d7 $3.20 is about $0.64; $1.50 \u2212 $0.64 is about $0.86.',
  bad:'Do both sides: pump savings $1.50, trip cost about $0.64. Y still wins by about $0.86.',
  why:'Neither absolute rule works: the detour does not automatically win or lose. The subtraction decides - here, Y wins by less than a dollar.'},
 {t:'try',q:'When is driving farther for cheaper gas NEVER worth it?',
  choices:[{label:'When the extra trip cost is bigger than the pump savings',ok:true},{label:'When the cheaper station is more than 5 miles away',ok:false},{label:'When you are in a hurry',ok:false},{label:'When gas costs more than $4 a gallon',ok:false}],
  hint:'It is always the same subtraction.',
  good:'Exactly. The rule has no mileage cutoff - only the math.',
  bad:'5 miles, $4 gas, being busy - none of those decide it. Only trip cost vs pump savings does.',
  why:'Fixed rules ("never drive more than 5 miles") break because the answer depends on the gap, the tank, and the mileage. The subtraction is the whole decision.'},
 {t:'tool',screen:'pacing-value',focus:'gas',h:'Try the gas calculator',body:'<p>Enter both stations, your tank, and the detour - see the real savings.</p>',cta:'Open the gas calculator'}
]},
'subscriptions-lesson':{intro:'Small monthly charges are yearly decisions in disguise.',steps:[
 {t:'teach',h:'Multiply by 12',
  body:'<p>$12.99/month sounds small. <b>$12.99 \u00d7 12 = $156/year</b> sounds different - because it is the same money.</p><p>Every subscription is a <i>yearly</i> decision wearing a monthly costume. Three "small" subs can quietly eat $400\u2013$500 a year.</p>'},
 {t:'example',h:'Maya audits her subs',story:'<p>Music $9.99 + video $15.99 + a fitness app $7.99 she opened twice.</p>',
  points:['Monthly total: $33.97','Yearly: $33.97 \u00d7 12 = <b>$407.64</b>','She cancels the fitness app: saves $95.88/year in 2 minutes.']},
 {t:'try',q:'Music $9.99/mo + video $15.99/mo. What is the yearly total?',
  choices:[{label:'About $312/year',ok:true},{label:'About $25.98/month - the monthly number is what matters',ok:false},{label:'About $26/year',ok:false},{label:'About $156/year',ok:false}],
  hint:'Add, then multiply by 12.',
  good:'Right: ($9.99 + $15.99) \u00d7 12 = $311.76.',
  bad:'($9.99 + $15.99) = $25.98/month. \u00d7 12 = $311.76/year.',
  why:'$25.98 feels small; $311.76 is the real decision size. Always multiply by 12.'},
 {t:'try',q:'Maya pays $7.99/mo for an app she has not opened in 3 months. Keep or cancel?',
  choices:[{label:'Keep - she might use it someday',ok:false},{label:'Keep - she already paid for 3 months, so canceling wastes that money',ok:false},{label:'Cancel - re-subscribe if she ever needs it',ok:true},{label:'Keep - canceling now means a rejoin fee later',ok:false}],
  hint:'Recurring cost needs recurring value.',
  good:'Right. $95.88/year for "might" is a bad trade.',
  bad:'Three unused months = the value is not recurring. Cancel; it takes 2 minutes to rejoin later.',
  why:'A subscription must earn its cost <i>every month</i>. "Might use it" is not earning. Cancel now, re-subscribe if life changes.'},
 {t:'try',q:'Maya has 4 subscriptions: $8, $12, $15, and $5 a month. She uses two regularly, one rarely, one never. What is the yearly cost of the two she barely touches?',
  choices:[{label:'$240/year',ok:true},{label:'$20/month - the monthly number is what matters',ok:false},{label:'$480/year',ok:false},{label:'$0 - unused subscriptions do not really count',ok:false}],
  hint:'Add the two, then multiply by 12.',
  good:'Right: ($15 + $5) \u00d7 12 = $240.',
  bad:'($15 + $5) = $20/month. Times 12 = $240/year of barely-used subscriptions.',
  why:'$20/month sounds like nothing; $240/year is a textbook bill. "Do not really count" is how they survive - make them count.'},
 {t:'try',q:'Maya\u2019s streaming service raises its price from $15.99 to $18.99. She barely notices. What should the raise trigger?',
  choices:[{label:'Nothing - $3 more is nothing',ok:false},{label:'A re-audit: does it still earn its cost every month at the new price?',ok:true},{label:'Cancel immediately - every price hike is a scam',ok:false},{label:'Downgrade the internet plan instead',ok:false}],
  hint:'Recurring cost needs recurring value - at the NEW price.',
  good:'Right. The value did not change; the price did. Re-run the test.',
  bad:'$18.99 \u00d7 12 = $227.88/year now. Does it still earn that?',
  why:'Price hikes count on you not noticing. Each one is a free reminder to ask: would I sign up today at this price? If not, cancel.'},
 {t:'tool',screen:'subscriptions',h:'Audit your subscriptions',body:'<p>List yours and see the yearly total - the number that actually matters.</p>',cta:'Open the subscription tracker'}
]}
});

/* ================= MODULES 4 & 5: built from adult-life content ================= */
import { ADULT_LIFE_MODULES } from './adult-life.js';
import { adultLifeAssessmentForSkill } from './adult-life-assessment.js';

const escHtml=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

function adultLifeLesson(id){
  const m=ADULT_LIFE_MODULES.find(x=>x.id===id);
  if(!m) return {intro:'',steps:[]};
  const correctChoice=m.practice.choices.find(c=>c.id===m.practice.correct);
  const correctFeedback=correctChoice?correctChoice.feedback:'Correct.';
  const steps=[
    {t:'teach',h:m.title+': what to know',
     body:'<p>'+escHtml(m.summary)+'</p><ul>'+m.durableConcepts.map(c=>'<li>'+escHtml(c)+'</li>').join('')+'</ul><p class="sub">Concepts last; rules, amounts, and forms change. When an answer depends on current rules, check the official source - never memorize a number as permanent.</p>'},
    {t:'try',q:m.practice.prompt,
     choices:m.practice.choices.map(c=>({label:c.label,ok:c.id===m.practice.correct,note:c.feedback})),
     hint:'Which choice protects the decision process - not just today, but as a habit?',
     good:correctFeedback,
     bad:'Not quite. Read what each choice actually does, then pick the one that protects the process.',
     why:correctFeedback}
  ];
  const transfer=adultLifeAssessmentForSkill(m.skill,'transfer');
  if(transfer){
    steps.push({t:'try',q:'Harder - same skill, new situation: '+transfer.question,
      choices:transfer.choices.map(c=>({label:c[1],ok:c[0]===transfer.good})),
      hint:'Ignore the new surface details. What is the underlying decision?',
      good:'Right. '+transfer.help,
      bad:'The situation changed but the skill did not. '+transfer.help,
      why:transfer.help});
  }
  return {intro:m.summary,steps};
}

Object.assign(LESSON_CONTENT,{
 'banking':adultLifeLesson('banking'),
 'first-job':adultLifeLesson('first-job'),
 'credit':adultLifeLesson('credit'),
 'scams':adultLifeLesson('scams'),
 'renting':adultLifeLesson('renting'),
 'utilities':adultLifeLesson('utilities'),
 'groceries':adultLifeLesson('groceries'),
 'transportation':adultLifeLesson('transportation'),
 'health-insurance':adultLifeLesson('health-insurance')
});

/* ================= MODULE 6: Future Money and Support ================= */
import { BENEFIT_TOPICS } from './benefits.js';

Object.assign(LESSON_CONTENT,{
'future-needs':{intro:'Emergencies are predictable in general and surprising in particular. Plan for the category.',steps:[
 {t:'teach',h:'You cannot predict it. You can still plan for it.',
  body:'<p>Nobody knows <i>when</i> the car will break down, the phone will die, or the medical bill will arrive. But every adult knows they <i>will</i> arrive.</p><p>Emergency money is not pessimism. It is <b>pre-deciding</b>: "when a surprise comes, it comes out of this bucket - not a credit card, not panic."</p><p>A starter emergency fund for a student: <b>$500\u2013$1,000</b>, or about one month of needs. Build it $10\u2013$20 at a time.</p>'},
 {t:'example',h:'Maya builds a buffer',story:'<p>Maya moves $10/week into emergency savings. Nothing dramatic.</p>',
  points:['After 6 months: ~$260.','After a year: ~$520.','Then her car needs a $300 repair.','It comes from the buffer. No credit card. No crisis. The plan worked.']},
 {t:'try',q:'Maya has $0 in emergency savings and a $400 car repair she must pay. What most likely happens?',
  choices:[{label:'It goes on a credit card, plus interest',ok:true},{label:'She borrows $400 from a friend - friend loans are always free',ok:false},{label:'The repair waits politely until she saves up',ok:false},{label:'Nothing - repairs are optional',ok:false}],
  hint:'Without a buffer, where does surprise money come from?',
  good:'Right. No buffer = borrowing, usually at high interest.',
  bad:'Repairs do not wait. Without savings, the money comes from borrowing - plus interest.',
  why:'This is the real cost of $0 emergency savings: a $400 repair becomes $400 + interest. The buffer breaks that chain.'},
 {t:'try',q:'Two students each save $20/week. One calls it "emergency money," the other just leaves it in checking. A $300 surprise hits. Who is better off?',
  choices:[{label:'The one who named it emergency money',ok:true},{label:'The one who left it in checking - it is easier to reach in an emergency',ok:false},{label:'No difference - same dollars',ok:false},{label:'No difference - the interest rate matters more than the label',ok:false}],
  hint:'What happens to unnamed money?',
  good:'Right. Named money has a job; unnamed money gets spent.',
  bad:'Same dollars, different fate: unnamed money leaks into daily spending. The label protects it.',
  why:'This is the deeper lesson: the <i>label</i> is the protection. Money with a job (emergency) survives; money without one quietly disappears into Wants.'},
 {t:'try',q:'Maya can save $15/week or $65/month toward her emergency buffer. Which builds it faster?',
  choices:[{label:'$65/month - bigger chunks build faster',ok:false},{label:'They are nearly identical - about $780/year either way. The habit matters more',ok:true},{label:'$15/week - weekly saving is always better',ok:false},{label:'Neither - small amounts never build a real buffer',ok:false}],
  hint:'Do the yearly math on both.',
  good:'Right: $15 \u00d7 52 = $780; $65 \u00d7 12 = $780.',
  bad:'$780 vs $780. The schedule is trivia - the automatic habit is the engine.',
  why:'People stall for months picking the "best" schedule while saving $0. Both build the same buffer; the one that happens automatically wins.'},
 {t:'try',q:'Maya\u2019s emergency fund is for surprises. Which of these is NOT its job?',
  choices:[{label:'A surprise car repair',ok:false},{label:'The spring-break trip she has been planning for months',ok:true},{label:'An urgent dental bill',ok:false},{label:'Replacing the laptop that just died before finals',ok:false}],
  hint:'Which one is not a surprise?',
  good:'Right. Planned trips need a goal fund, not the emergency fund.',
  bad:'Three surprises, one plan. The trip is predictable - it gets its own savings job.',
  why:'Raiding emergency money for planned fun is how the fund is empty when the real surprise arrives. Surprises get the emergency fund; plans get goal savings.'},
 {t:'tool',screen:'save',h:'Start the buffer',body:'<p>Set a savings target and watch small weekly moves add up to a real buffer.</p>',cta:'Open savings tools'}
]},
'benefits-lesson':{intro:'Support programs exist. Learn how to read them correctly.',steps:[
 {t:'teach',h:'Versioned information, not memorized numbers',
  body:'<p>Programs like SSI, SSDI, and ABLE accounts have <b>rules that change</b>: amounts update yearly, eligibility depends on your situation.</p><p>So do not memorize numbers. Learn the <b>stable concepts</b>:</p><ul>'+BENEFIT_TOPICS.slice(0,3).map(t=>'<li><b>'+escHtml(t.title)+':</b> '+escHtml(t.summary)+'</li>').join('')+'</ul><p class="sub">Current figures are labeled with their year and source inside the Benefits section. When an answer depends on a current rule, check the official source.</p>'},
 {t:'example',h:'Maya reads a benefit correctly',story:'<p>Maya hears "SSI pays $X a month" from a friend.</p>',
  points:['She checks the Benefits section: the figure is labeled with its year and source.','She reads the <i>stable concept</i>: SSI has income and resource rules; work does not automatically end it.','She does not treat the friend\u2019s number as permanent - she checks the official source.']},
 {t:'try',q:'A friend says "I heard SSI pays $994 a month, so that is what you would get." What is wrong with treating that as your answer?',
  choices:[{label:'Nothing - a number is a number',ok:false},{label:'Nothing - once published, official numbers never change',ok:false},{label:'Amounts change yearly and depend on your situation - check the current official source',ok:true},{label:'Average three friends\u2019 answers - the crowd is usually right',ok:false}],
  hint:'What did you learn about versioned information?',
  good:'Right. Concepts last; numbers expire.',
  bad:'Figures are year-labeled for a reason: they change. And eligibility is individual.',
  why:'The $994 figure is real <i>for its year and situation</i> - not a permanent personal quote. Always verify current rules at the official source.'},
 {t:'try',q:'Why does NWS teach the concept ("SSI has income and resource rules") instead of just the current payment amount?',
  choices:[{label:'Concepts stay useful after numbers change',ok:true},{label:'Because the amount is the same for everyone, so it does not matter',ok:false},{label:'Numbers are not important',ok:false},{label:'Because concepts get tested and numbers do not',ok:false}],
  hint:'Which one survives a new year?',
  good:'Exactly. Learn the durable part; look up the changeable part.',
  bad:'The amount will change next year. The concept - that rules exist and where to check them - lasts.',
  why:'This is a thinking skill, not trivia: know <i>that</i> rules exist, <i>what kind</i> they are, and <i>where</i> to verify them. That survives every update.'},
 {t:'try',q:'Maya reads a 2022 article saying a program\u2019s limit is $2,000. It is now 2026. What should she do with that number?',
  choices:[{label:'Use it - published numbers are permanent',ok:false},{label:'Check the current official source - a 4-year-old figure has expired',ok:true},{label:'Assume the limit is now $0',ok:false},{label:'Ask social media what the new number is',ok:false}],
  hint:'What did you learn about versioned information?',
  good:'Right. Four years is several rule changes ago.',
  bad:'Year-labeled figures expire. The official source has the current one.',
  why:'Old articles do not update themselves. Treating a 2022 number as current is how people plan around money that no longer exists.'},
 {t:'try',q:'Maya needs the current rules for a benefit program. Which source should she trust most?',
  choices:[{label:'The program\u2019s official site',ok:true},{label:'A viral video that explains it simply',ok:false},{label:'A friend who receives the benefit',ok:false},{label:'An old textbook from the library',ok:false}],
  hint:'Who actually writes the rules?',
  good:'Exactly. The rule-writer outranks every retelling.',
  bad:'Videos simplify, friends generalize, textbooks age. The official source is current by definition.',
  why:'This is the versioned-information skill in action: when the answer depends on current rules, go to the source that makes them. Everything else is a copy of a copy.'},
 {t:'tool',screen:'benefits',h:'Explore the Benefits section',body:'<p>See how figures are year-labeled and sourced - and where the official links live.</p>',cta:'Open Benefits'}
]},
'decision-routine':{intro:'Put the whole routine together on one real scenario.',steps:[
 {t:'teach',h:'The full NWS decision routine',
  body:'<p>Everything in this course compresses into one routine. Run it whenever money arrives or a big decision looms:</p><ol><li><b>Available?</b> Balance \u2212 scheduled, pending, and promised money.</li><li><b>How long?</b> How much time must it cover?</li><li><b>Needs first.</b> Protect every required cost.</li><li><b>Savings next.</b> Move future money aside before spending.</li><li><b>Pace it.</b> Safe money \u00f7 time = your speed limit.</li><li><b>Spend smart.</b> Was I going to buy it anyway? What will I actually use?</li><li><b>Overspent?</b> Recalculate from what remains - never from the original plan.</li></ol>'},
 {t:'example',h:'Maya runs the whole routine',story:'<p>Maya gets $600 for the month.</p>',
  points:['<b>Available?</b> $600, nothing pending \u2192 $600.','<b>How long?</b> 30 days.','<b>Needs:</b> $350 rent share + food \u2192 protect it.','<b>Savings:</b> $60 to the emergency buffer.','<b>Pace:</b> ($600 \u2212 $350 \u2212 $60) \u00f7 30 = <b>$6.33/day</b>.','<b>Spend smart:</b> the "deal" she sees gets the "was I going to buy it anyway" test.','<b>Overspent mid-month?</b> New pace from what remains.']},
 {t:'try',q:'Mid-month, Maya realizes she spent $100 more than planned. What are her next two moves, in order?',
  choices:[{label:'Feel bad, then keep spending the same way',ok:false},{label:'Cut spending to $0 for the rest of the month to make up for it',ok:false},{label:'Find the money remaining, then set a new pace from it',ok:true},{label:'Borrow from next month to stay on the old plan',ok:false}],
  hint:'Step 7 of the routine.',
  good:'Right: remaining money \u00f7 remaining time. The plan updates; it does not punish.',
  bad:'Step 7: recalculate from what REMAINS. Find it, divide by time left.',
  why:'Overspending is data, not failure. The routine\u2019s last step exists for exactly this: new pace = remaining \u00f7 remaining time.'},
 {t:'try',q:'Which order does the routine protect money in?',
  choices:[{label:'Wants, then Needs, then Savings',ok:false},{label:'Any order - the total at month-end is all that matters',ok:false},{label:'Needs, then Savings, then Wants from what is left',ok:true},{label:'Savings only - Needs can wait',ok:false}],
  hint:'Steps 3, 4, 5.',
  good:'Right. Needs \u2192 Savings \u2192 Wants. In that order, every time.',
  bad:'Needs first (you must function), Savings second (future you), Wants last (from what is left).',
  why:'The order IS the routine. Flip it - Wants first - and Needs and Savings get whatever happens to be left, which is usually nothing.'},
 {t:'try',q:'Maya gets $800 for the month. Put the routine steps in order: (a) set the daily pace, (b) protect the $420 of needs, (c) move savings aside, (d) check for pending and scheduled money.',
  choices:[{label:'d, b, c, a',ok:true},{label:'a, b, c, d - pace first, then protect',ok:false},{label:'b, a, c, d',ok:false},{label:'c, b, d, a - savings first',ok:false}],
  hint:'Available, then Needs, then Savings, then pace.',
  good:'Right: check what is real, protect needs, move savings, then pace what is left.',
  bad:'The order is the routine: (d) available, (b) needs, (c) savings, (a) pace.',
  why:'Each step needs the one before it: you cannot pace money until savings is moved, and you cannot move savings until needs are protected. Order is the whole game.'},
 {t:'try',q:'Maya runs the routine and her pace comes out to $4/day. She feels discouraged. What is the most useful next thought?',
  choices:[{label:'The routine failed - $4/day is not a real plan',ok:false},{label:'The routine worked: now she sees the real number and can adjust needs or income',ok:true},{label:'Ignore the pace - routines are for bigger budgets',ok:false},{label:'Borrow money to raise the pace',ok:false}],
  hint:'Is a true-but-small number a failure of the tool, or useful information?',
  good:'Right. A harsh true number beats a comfortable false one.',
  bad:'$4/day is data, not failure. Now she can cut a need, add income, or adjust the goal.',
  why:'The routine\u2019s job is the truth, not comfort. $4/day tells her exactly what has to change - far more useful than a $20/day fantasy that collapses on the 12th.'},
]}
});
